### PR TITLE
Upgrade to read the new project format

### PR DESCRIPTION
**Pull request by flagbug**
This PR basically does multiple things that go hand-in-hand

- Update dotnet-outdated itself to run on .NET Core 2.0 and the new package format
- Update the parser to read the new `.csproj` package format instead of the old project.json

### CODE REVIEW

**Comment by goenning** [comment]
Looks great, thanks for your contribution! 

I'll give it a try later this week and push a new version to NuGet.

**Comment by flagbug** [comment]
@goenning Thanks for merging this, and yup, a new NuGet release would be great!

**Comment by goenning** [comment]
Version `2.0.0` is available on NuGet!

**Comment by flagbug** [comment]
Awesome!

**Pull request merged**
